"""add popularity to tracks

Revision ID: 85b3e4ef08d1
Revises: 7c9405c7e3c1
Create Date: 2026-04-10 22:03:48.175606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b3e4ef08d1'
down_revision: Union[str, Sequence[str], None] = '7c9405c7e3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('popularity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'popularity')
    # ### end Alembic commands ###
