"""Candidate retrieval — loads the Annoy index and returns nearest neighbor track IDs."""

import json
import os

import joblib
import numpy as np
from annoy import AnnoyIndex

from app.models import Track

_MODELS_DIR = "models"
_N_FEATURES = 9

# Load artifacts once at module import time — not on every request.
# All three files are generated by scripts/build_index.py.
_scaler = joblib.load(os.path.join(_MODELS_DIR, "scaler.pkl"))

_index = AnnoyIndex(_N_FEATURES, "angular")
_index.load(os.path.join(_MODELS_DIR, "annoy_index.ann"))

with open(os.path.join(_MODELS_DIR, "track_id_map.json")) as _f:
    _track_ids: list[str] = json.load(_f)


def track_to_vector(track: Track) -> list[float]:
    """Extract raw audio features from a Track ORM object in index build order."""
    return [
        track.energy,
        track.valence,
        track.danceability,
        track.tempo,
        track.acousticness,
        track.instrumentalness,
        track.loudness,
        track.speechiness,
        track.popularity,
    ]


def get_candidates(query_vector: list[float], n: int = 500) -> list[str]:
    """Normalize a raw feature vector and return the n nearest spotify_ids from the index."""
    raw = np.array(query_vector, dtype=float).reshape(1, -1)
    normalized = _scaler.transform(raw)[0].tolist()
    positions = _index.get_nns_by_vector(normalized, n)
    return [_track_ids[pos] for pos in positions]
